Squashed commit of the following:
commit 12e11ac3d78988c9a76d79701f1cc05316054c61
Author: anggarapp <anggaraperpe@gmail.com>
Date:   Sun Jun 6 13:24:50 2021 +0700

    change model location to local

commit 9c39335bda4d5b35487afee740f8697cff55513f
Author: anggarapp <anggaraperpe@gmail.com>
Date:   Sun Jun 6 06:56:52 2021 +0700

    change model location to local

commit b3d5f630b2a78be8f958db18f2866b5e8acd242f
Author: anggarapp <anggaraperpe@gmail.com>
Date:   Sun Jun 6 06:42:33 2021 +0700

    model consuming error solved

commit c0bcf927749cfda2f31e30498e1bbcca55ed4bfd
Merge: d8f7bf3 52111cd
Author: anggarapp <anggaraperpe@gmail.com>
Date:   Sun Jun 6 04:21:56 2021 +0700

    Merge branch 'main' of https://github.com/anggarapp/SmartRicePriceControl into main

commit d8f7bf389f6802f751116c1bc77992584c34bc6f
Author: anggarapp <anggaraperpe@gmail.com>
Date:   Sun Jun 6 04:21:12 2021 +0700

    ValueError: Input 0 of layer sequential is incompatible with the layer:...

commit 52111cdc7e263b466e164cbe22c1dcf4985a6fed
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sun Jun 6 03:57:28 2021 +0700

    Add files via upload

commit 015c71a0843e6ba0442b23b2b1e7c3584a4490c5
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sun Jun 6 03:57:06 2021 +0700

    Delete Machine Learning/Dataset/Cuaca/Tuban directory

commit d29b0165de6c3cc75330c53997785bcd6cbf6b54
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sun Jun 6 03:56:59 2021 +0700

    Delete Machine Learning/Dataset/Cuaca/Lamongan directory

commit 224539c98f5a732e908175d4c675ca9b9b3e8d4f
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sun Jun 6 03:56:51 2021 +0700

    Delete Machine Learning/Dataset/Cuaca/Banyuwangi directory

commit 20e529079ee9ce440f37d24c37ee52dae41949cf
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sun Jun 6 03:56:25 2021 +0700

    Add files via upload

commit c271de3308cb86343aee811b73d1ab00863b4a67
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sun Jun 6 03:55:58 2021 +0700

    Delete Database - Sebelom dikasih diyan.csv

commit aa7e432fcbf39b25d7c17d9108fae5aff7ce4361
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sun Jun 6 03:54:49 2021 +0700

    revisi terakhir

commit 1a5c69a5149d4c5a96a166ebde895251efb36b7d
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sun Jun 6 03:51:26 2021 +0700

    revisi terakhir

commit 40114be0d2b806feea7e54b487b8abd6580f49cc
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sun Jun 6 03:50:46 2021 +0700

    revisi terakhir

commit 4ad11dc2d916020a72ee99d2268473e8f2de9a82
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sun Jun 6 03:49:04 2021 +0700

    revisi terakhir

commit 7fb80544f7ca37da48614ba8819ddfbbe10b6423
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sun Jun 6 03:47:48 2021 +0700

    revisi terakhir

commit 1f54fd8ce5d2efdeddf40d4e3f9da8c0d401cfe0
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sat Jun 5 13:14:55 2021 +0700

    Add files via upload

commit c0027b7c1d76fc791b466fcdc207e44e4bb4f1ec
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sat Jun 5 13:12:09 2021 +0700

    revisi terakhir

commit 955840c8fb3f59ff14244144701007f504fe0782
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sat Jun 5 13:08:39 2021 +0700

    revisi terakhir

commit 1cf5e72e2b8c28a3e8090ca4d88698b6c49e6a38
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sat Jun 5 13:06:30 2021 +0700

    revisi terakhir

commit 055bdb2b27b9ce50393ddc705933896077f3ed43
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sat Jun 5 13:03:23 2021 +0700

    revisi terakhir

commit 3cb44b0cf2dedebc2b512b24c84934748c561655
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Sat Jun 5 13:02:42 2021 +0700

    revisi_terakhir

commit fd04ef1ad829556258edb8528ed353ac482e36f6
Merge: 9e75e37 a77a1ff
Author: Anggara Permana Putra <79002510+anggarapp@users.noreply.github.com>
Date:   Sat Jun 5 04:18:21 2021 +0700

    Merge pull request #12 from anggarapp/main

    untested api endpoint

commit a77a1ffa3202591e3635cb91b38cfea90b8c98b6
Author: anggarapp <anggaraperpe@gmail.com>
Date:   Sat Jun 5 04:14:58 2021 +0700

    test +4 API

commit 4bd648df7cd6469f837cfd60fab3e925751c1778
Merge: cafd7d6 9e75e37
Author: Anggara Permana Putra <79002510+anggarapp@users.noreply.github.com>
Date:   Sat Jun 5 02:29:11 2021 +0700

    Merge branch 'u1-byte:main' into main

commit 9e75e37f1d9c226979cafebc19d73f55a3f6a8c9
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Fri Jun 4 23:09:55 2021 +0700

    Add files via upload

commit 5320dcc7f73634885704db838fe56d73a991a88e
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Fri Jun 4 23:09:22 2021 +0700

    Add files via upload

commit d6bf11cc8befa8b8f200fd6e26aae76791c538d0
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Fri Jun 4 23:05:55 2021 +0700

    revisi7

commit 8ba5d309600cf4342d2cd8e254b2e7acf9a0803b
Merge: e31f456 30daf33
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Fri Jun 4 18:28:32 2021 +0800

    Merge branch 'android' into main

commit 30daf33e32031ecd33f1abd11137e0140a79efe5
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Fri Jun 4 18:10:53 2021 +0800

    fix xml

commit 3c222ee4bd471a1c539a5a280e12093d5aa00b8b
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Fri Jun 4 18:02:48 2021 +0800

    add assets

commit 21228332c51eeccc04d5f146568d474c114a6233
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Fri Jun 4 16:16:38 2021 +0800

    finishing apps

commit e31f456330bbc0b189a0ad659bbe07d1d16bac57
Author: Anggara Permana Putra <79002510+anggarapp@users.noreply.github.com>
Date:   Thu Jun 3 15:55:54 2021 +0700

    Delete cred.json

commit cafd7d6beac4819904da5ae8df7a5c1de0d5ea3c
Author: Anggara Permana Putra <79002510+anggarapp@users.noreply.github.com>
Date:   Thu Jun 3 15:53:32 2021 +0700

    Delete cred.json

commit c8fced0364144781288d13f7c7a9ef3f06b7d9d0
Author: anggarapp <anggaraperpe@gmail.com>
Date:   Thu Jun 3 15:52:42 2021 +0700

commit 247d75c6028f73abc6214e9d9235f253a5dbcd4f
Author: anggarapp <anggaraperpe@gmail.com>
Date:   Thu Jun 3 15:51:43 2021 +0700

commit 1ce55d0451e9bfdd10dab7ebc672f7097af13099
Author: anggarapp <anggaraperpe@gmail.com>
Date:   Thu Jun 3 15:48:57 2021 +0700

commit e747100bc162e34a6341e0833aab0b51b2da7b67
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Thu Jun 3 16:05:11 2021 +0800

    setup dummy data

commit 98d8aea43ef6bfba0caf504b062c1a77ab1eb23c
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Thu Jun 3 15:45:52 2021 +0800

    fix xml

commit 005205c2b769db94f18d95cc7464292fcac84e4f
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Thu Jun 3 13:32:38 2021 +0800

    edit location activity and delete design link

commit 0dc9c7f8dd1f6c69e2eee7af861cc0e6c7228822
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Thu Jun 3 00:58:39 2021 +0800

    add loading

commit 72b37db8c6c666c219d3caeb1c39962b1b0a19b0
Author: Yuma Gunawan <69004784+u1-byte@users.noreply.github.com>
Date:   Wed Jun 2 22:43:28 2021 +0800

    change title project

commit 4cf604ea61236da0604633f6ade5b27d1a4f9d84
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Wed Jun 2 21:31:11 2021 +0800

    adding parcelize to data

commit 42e4a8d182b99db8028ece652e21ebacd42ebf37
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 18:51:01 2021 +0700

    revisi2

commit c6187fba7fc11da909589cf8cc4158577a4ec076
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Wed Jun 2 19:28:25 2021 +0800

    api success

commit 843efad40e3e8227a79bd7e7333dd691e8381bb9
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 18:23:24 2021 +0700

    revisi2

commit 848c26534caa9ca52b62eb6b4273677fb7363c16
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Wed Jun 2 17:40:08 2021 +0800

    add network setup

commit dbb9a67b3e2754f4a171556be7633d5e4ccc5d59
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 14:48:54 2021 +0700

    Add files via upload

commit ad79f5d90a6964861968060b76961ddc2aae25a4
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 14:48:10 2021 +0700

    revisi1

commit 1ffdd8b5baeadc13bb6387be81e36c26a9e77493
Merge: d785c4a d093196
Author: Anggara Permana Putra <79002510+anggarapp@users.noreply.github.com>
Date:   Wed Jun 2 09:11:40 2021 +0700

    Merge pull request #11 from anggarapp/main

    Add google cloud run deployment option

commit d0931967d8b29e71661f51d1c839abd007b34073
Author: anggarapp <anggaraperpe@gmail.com>
Date:   Wed Jun 2 08:07:11 2021 +0700

    add support for GCR

commit 8abc6b97db653b9f3da630f0bb37e638d8a7a629
Author: anggarapp <anggaraperpe@gmail.com>
Date:   Wed Jun 2 08:05:15 2021 +0700

    add support for GCR

commit 6a80dc5052b16dcb2eef442727cd3d7f81e7bff4
Author: anggarapp <anggaraperpe@gmail.com>
Date:   Wed Jun 2 08:03:36 2021 +0700

    add support for GCR

commit 85eb815cbce6f2c9935bcb01e6d6132a3837f20b
Author: anggarapp <anggaraperpe@gmail.com>
Date:   Wed Jun 2 05:20:52 2021 +0700

commit d785c4ab13054f38a9a20506a9c8ffb1d5db3be1
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 03:59:50 2021 +0700

    Add files via upload

commit 48aa58ed139901cc68cd3cbd1c320a0905822a19
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 03:59:01 2021 +0700

    revisi1

commit 1a8bc82e1ddf00f037f0a113c3e8c2505fc1a61c
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 03:12:37 2021 +0700

    Add files via upload

commit c01d111ede1487a21e17846227c5650b21fb41cf
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 03:11:19 2021 +0700

    revisi1

commit c94c50dc4e0b191c04b83a116055f7e64f08df23
Merge: 8bd2482 59fc541
Author: Anggara Permana Putra <79002510+anggarapp@users.noreply.github.com>
Date:   Wed Jun 2 03:03:45 2021 +0700

    Merge pull request #10 from anggarapp/main

    revisi 5

commit 59fc541377ffcc00f41bf0e9edeb21d583d39444
Merge: 45875f3 8bd2482
Author: Anggara Permana Putra <79002510+anggarapp@users.noreply.github.com>
Date:   Wed Jun 2 03:03:33 2021 +0700

    Merge branch 'main' into main

commit 45875f34df2bdb161acbf36cb1e9618f1533e714
Author: anggarapp <anggaraperpe@gmail.com>
Date:   Wed Jun 2 02:52:54 2021 +0700

    solve revisi 5

commit 8bd2482d0225c094e3d83328e13a39d6453b5474
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 02:44:16 2021 +0700

    Add files via upload

commit ba7bc2d15a5366074086835d54dadb2ccf2a9e3a
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 02:43:38 2021 +0700

    Add files via upload

commit 8bf236917a7740bf27b865bbb2b7e29cb6839b7a
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 02:42:59 2021 +0700

    revisi7

commit fb95f6ad1b00ebb719d27d3c78142ebf18d68704
Author: anggarapp <anggaraperpe@gmail.com>
Date:   Wed Jun 2 02:29:44 2021 +0700

commit 9589287b5436a3942db848d0e23e8b59102bfa0a
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 02:17:07 2021 +0700

    Add files via upload

commit 487c754baef52b9ab88c0af9c0f5f4d3608bbc6a
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 02:10:11 2021 +0700

    Delete ML_Testing_Model-Copy-1.ipynb

commit ed74b082692bc09d789e4e0835af6958509c6201
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 02:09:59 2021 +0700

    Delete [Building+Testing]ML_Model.ipynb

commit 210ab82d327169853fee3721f42f1fdedb360615
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 02:09:42 2021 +0700

    Add files via upload

commit 1062ecf472efe769d15bf1f10a46ba6bb1ef33db
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 02:09:15 2021 +0700

    Delete model.h5

commit 677bec5f52704ee7c980cc47a483f2fa394d5f4e
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 02:08:46 2021 +0700

    revisi6

commit 3ebe960f8db8e34f0d0a07d21d807e67f8974291
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 01:47:12 2021 +0700

    Add files via upload

commit b22a6284a3ff323462601102cf50e28ed402237d
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 01:46:57 2021 +0700

    revisi1

commit 167a306616be1e755025b8c5cdde6023a38f8d5a
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Wed Jun 2 01:44:35 2021 +0700

    revisi1

commit 11f222a54a003cc7a2461a37d12277bbdb672246
Merge: 2c7c776 bd3973a
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Tue Jun 1 22:44:25 2021 +0800

    Merge branch 'android' into main

commit 2c7c7762e249abdea537245d0d4d42151d43be17
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Tue Jun 1 22:43:56 2021 +0800

    add initial readme

commit bd3973aa03a72e9925465a87bfc2b7e152344195
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Tue Jun 1 22:38:07 2021 +0800

    add img assets

commit ba3ba236b75ef8e57e39b7c9aace60b11b3a4e5b
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Tue Jun 1 22:37:10 2021 +0800

    setup about activity

commit 5f15b42d40d2254f2af37471f0874bcf176f5424
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Tue Jun 1 22:13:06 2021 +0800

    setup result activity

commit 757dd0ba9bf95d74aa2b4eaf4e1a2d5a8685f8ec
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Tue Jun 1 21:48:00 2021 +0800

    change manifest

commit c16836b2e7ef2a86431c7261798c3c413889769c
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Tue Jun 1 21:47:01 2021 +0800

    delete file

commit b17356ba08b2f41f9c2107e75e17a9dafec5a2ff
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Tue Jun 1 21:45:04 2021 +0800

    setup main activity

commit 3541eb2fd9f8cc33e24d1ac5160b61f311062018
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Tue Jun 1 20:22:26 2021 +0700

    Add files via upload

commit 14db5ab29a35b6d8d7481cfccffa46c1e28134ea
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Tue Jun 1 20:21:40 2021 +0700

    Add files via upload

commit 07e9b7452d1972e93f7340026c80790389deee48
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Tue Jun 1 20:21:01 2021 +0700

    Create notes.txt

commit e98bf57c78beafcc7e95846faec9385741d0143e
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Tue Jun 1 20:20:20 2021 +0700

    Add files via upload

commit f2fb26a7b8a663d16d6dc4eee3f0ec4a1615fa34
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Tue Jun 1 19:56:22 2021 +0700

    revisi5

commit fcb19953bc6d9b5252bc08ea982b2660d83be73d
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Tue Jun 1 19:55:44 2021 +0700

    Delete ML_Building_Model.ipynb

commit c2e3e04ae801747f83576dd8cb26734890f2b6c3
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Tue Jun 1 19:55:34 2021 +0700

    Delete ML_Testing_Model.ipynb

commit cf4678b0e1b824b71b1a06ba9728060929f7f3c6
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Tue Jun 1 19:47:42 2021 +0700

    Add files via upload

commit bd2e6909f8d7bd530daa1f80d2c1799fd9db3f9a
Author: frozin01 <49452458+frozin01@users.noreply.github.com>
Date:   Tue Jun 1 19:46:24 2021 +0700

    revisi5

commit 1c0de4bc06a73019158ac14f54004afead8f564e
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Tue Jun 1 17:49:41 2021 +0800

    main 50%

commit ee5047c6ab90e05dfa9526346e39631b203fa470
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Tue Jun 1 16:31:48 2021 +0800

    setup onboarding and add about

commit bcdad989ec38e53c5057021a08f6f29972196ba7
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Tue Jun 1 15:59:38 2021 +0800

    add on boarding page

commit edf488e14dad01d01fa08990128a52e6f77902c6
Merge: c316f44 90f795a
Author: Anggara Permana Putra <79002510+anggarapp@users.noreply.github.com>
Date:   Tue Jun 1 08:37:07 2021 +0700

    Merge pull request #9 from anggarapp/main

    add backend requirement

commit c316f44d1730042db68ee7896e9ddbc698434782
Merge: dac6fdc ff5adb6
Author: Anggara Permana Putra <79002510+anggarapp@users.noreply.github.com>
Date:   Tue Jun 1 08:28:08 2021 +0700

    Merge pull request #8 from anggarapp/main

    solve revisi-4 of ML model

commit 6862cd470b4d1fef80e3849ac8315674df297dda
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Tue Jun 1 01:22:28 2021 +0800

    set setup location xml

commit 77aeea62f55d1dd08f8f3d627e769003f3876f26
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Tue Jun 1 00:48:29 2021 +0800

    add logo and font style asset

commit 1f193aef7ace72c0e060f823f798af99d95a0138
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Tue Jun 1 00:17:43 2021 +0800

    add initial adapter and activity

commit aecbff69fef4c4c04aeffa7eb65bda4c13f09ca8
Author: Yuma Gunawan <amazingyuma0@gmail.com>
Date:   Tue Jun 1 00:04:50 2021 +0800

    add gradle xml